In [13]:
from rbpf_ou.src.data import get_results, WORLDCUP_2026_TEAMS
from datetime import datetime
import pandas as pd

df, results, team_id_to_name = get_results(
    start_date="2000-01-01", 
    end_date=datetime.today().strftime("%Y-%m-%d"), 
    teams_only=WORLDCUP_2026_TEAMS,
    include_friendly=False,
)
df.tail()

           date  home_team  ... home_team_id  away_team_id
1894 2026-07-11  Argentina  ...            1            42
1895 2026-07-14     France  ...           17            40
1896 2026-07-15    England  ...           16             1
1897 2026-07-18     France  ...           17            16
1898 2026-07-19      Spain  ...           40             1

[5 rows x 14 columns]

In [14]:
df[
    (df['tournament'] == "FIFA World Cup") & 
    (df['date'].dt.year == 2026)
][:20]

           date      home_team  ... home_team_id  away_team_id
1795 2026-06-11         Mexico  ...           26            38
1796 2026-06-11    South Korea  ...           39            12
1797 2026-06-12  United States  ...           45            32
1798 2026-06-12         Canada  ...            7             5
1799 2026-06-13      Australia  ...            2            44
1800 2026-06-13          Haiti  ...           20            36
1801 2026-06-13          Qatar  ...           34            42
1802 2026-06-13         Brazil  ...            6            27
1803 2026-06-14        Germany  ...           18            11
1804 2026-06-14    Ivory Coast  ...           23            14
1805 2026-06-14    Netherlands  ...           28            24
1806 2026-06-14         Sweden  ...           41            43
1807 2026-06-15        Belgium  ...            4            15
1808 2026-06-15           Iran  ...           21            29
1809 2026-06-15          Spain  ...           40             8
1810 2026-06-15   Saudi Arabia  ...           35            46
1811 2026-06-16      Argentina  ...            1             0
1812 2026-06-16        Austria  ...            3            25
1813 2026-06-16           Iraq  ...           22            30
1814 2026-06-16         France  ...           17            37

[20 rows x 14 columns]

In [16]:
df[
    (df['home_team'] == "Croatia") | (df['away_team'] == "Croatia")
]

           date       home_team  ... home_team_id  away_team_id
63   2000-09-02         Belgium  ...            4            10
75   2000-10-11         Croatia  ...           10            36
155  2001-09-01        Scotland  ...           36            10
166  2001-10-06         Croatia  ...           10             4
200  2002-06-03         Croatia  ...           10            26
...         ...             ...  ...          ...           ...
1768 2025-10-09  Czech Republic  ...           12            10
1817 2026-06-17         England  ...           16            10
1842 2026-06-23          Panama  ...           31            10
1861 2026-06-27         Croatia  ...           10            19
1878 2026-07-02        Portugal  ...           33            10

[88 rows x 14 columns]